stages:    
  - project_build
  - docker_build
  - docker_push
  - cleanup

cache:
  paths:
    - node_modules/

image: creatiwww/docker-compose:latest
services:
  - docker:dind

project_build_job:
  stage: project_build
  image: node:20-alpine
  tags:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
  script:
    - npm install pnpm -g
    - pnpm install --silent
    - pnpm prettier
    - pnpm build

docker_build_job:
  stage: docker_build
  tags:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
  script:
    - docker build -t your-language:latest .

docker_push_job:
  stage: docker_push
  tags:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
  before_script:
    - docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASS"
  script:
    - docker push your-language:latest

cleanup_job:
  stage: cleanup
  tags:
    - build
  script:
    - echo "Cleaning up workspace..."
    - docker system prune -af
  when: always
  
