image: node:20

steps:
  - step: &build
    name: Build checking
    caches:
      - node
    script:
      - npm install -g pnpm
      - pnpm install
      - pnpm prettier
      - pnpm build

pipelines:
  pull-requests:
    development:
      - step: *build
