image: node:20

definitions:
  steps:
    - step: &build
        name: Build checking
        caches:
          - node
        script:
          - npm install -g pnpm
          - pnpm install
          - pnpm run prettier
          - pnpm build

pipelines:
  pull-requests:
    'feature/*':
      - step: *build

    'fix/*':
      - step: *build

  branches:
    development:
      - step:
          name: Merge in development
          caches:
            - node
          script:
            - echo "🧪 Runs only on merge into development"

    main:
      - step:
          name: Merge in main
          caches:
            - node
          script:
            - echo "🧪 Runs only on merge into main"