networks:
  your-language:
    driver: bridge

volumes:
  postgres-data:

services:
  next-js:
    platform: linux/amd64
    image: next-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - '3001:3001'
    env_file:
      - .env
    environment:
      - PORT=3001
    restart: always
    networks:
      - your-language
    depends_on:
      - db
    # volumes:
    #   - ./app:/app
    #   - /app/node_modules
    #   - /app/.next

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - your-language
    depends_on:
      - next-js

  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - your-language
