FROM node:20-alpine AS builder

RUN npm install -g pnpm

WORKDIR /app

ARG NEXT_PUBLIC_APP_HOST

ENV NEXT_PUBLIC_APP_HOST=$NEXT_PUBLIC_APP_HOST

COPY package.json /app
COPY pnpm-lock.yaml /app

COPY . .

RUN pnpm install

RUN pnpm build

EXPOSE 3000

CMD [ "pnpm", "start" ]
