name: CD

on:
  push:
    branches:
      - development
      - main

jobs:
  migrate_and_seed:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=true pnpm generate

      - name: Run Migrations
        run: pnpm migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Seed Database
        run: pnpm seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  docker_build_and_push:
    needs: migrate_and_seed
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_APP_HOST=${{ secrets.NEXT_PUBLIC_APP_HOST }} \
            --build-arg NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            --build-arg NEXT_PUBLIC_APP_ENV=${{ secrets.NEXT_PUBLIC_APP_ENV }} \
            --build-arg NEXT_PUBLIC_DICTIONARY_API_URL=${{ secrets.NEXT_PUBLIC_DICTIONARY_API_URL }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }} \
            --build-arg AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }} \
            --build-arg AUTH_GITHUB_ID=${{ secrets.AUTH_GITHUB_ID }} \
            --build-arg AUTH_GITHUB_SECRET=${{ secrets.AUTH_GITHUB_SECRET }} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }} \
            --build-arg LANGCHAIN_ENDPOINT=${{ secrets.LANGCHAIN_ENDPOINT }} \
            --build-arg LANGCHAIN_PROJECT=${{ secrets.LANGCHAIN_PROJECT }} \
            --build-arg LANGCHAIN_TRACING_V2=${{ secrets.LANGCHAIN_TRACING_V2 }} \
            --build-arg MAILER_HOST=${{ secrets.MAILER_HOST }} \
            --build-arg MAILER_PASS=${{ secrets.MAILER_PASS }} \
            --build-arg MAILER_PORT=${{ secrets.MAILER_PORT }} \
            --build-arg MAILER_USER=${{ secrets.MAILER_USER }} \
            --build-arg STORAGE_ACCESS_KEY=${{ secrets.STORAGE_ACCESS_KEY }} \
            --build-arg STORAGE_ACCESS_KEY_ID=${{ secrets.STORAGE_ACCESS_KEY_ID }} \
            --build-arg STORAGE_ID=${{ secrets.STORAGE_ID }} \
            --build-arg STORAGE_NAME=${{ secrets.STORAGE_NAME }} \
            --build-arg AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} \
            --build-arg AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -t your-language -f docker/Dockerfile.github .

      - name: Tag Docker image
        run: docker tag your-language:latest ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.ECR_REPOSITORY }}:latest

  deploy_to_ecs:
    needs: docker_build_and_push
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Stop running task
        run: |
          TASK_ARN=$(aws ecs list-tasks \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service-name ${{ secrets.ECS_SERVICE }} \
            --query "taskArns[0]" \
            --output text)

          if [ "$TASK_ARN" != "None" ]; then
            echo "Stopping task: $TASK_ARN"
            aws ecs stop-task --cluster ${{ secrets.ECS_CLUSTER }} --task $TASK_ARN
          fi

      - name: Force ECS deployment
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE }} --force-new-deployment

  notify_main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Log message
        run: echo "🧪 Runs only on merge into main!"
